/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TourJava;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author skylar
 */
public class NotepadAbout extends javax.swing.JDialog {

    /**
     * Creates new form NotepadAbout
     */
    ImageIcon logo=new ImageIcon(getClass().getClassLoader().getResource("Images/Notepad.png"));
    JLabel l1,l2,l3;
    JButton b1;
    
    public NotepadAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
        super.setTitle("Notepad About");
        this.setIconImage(logo.getImage());
        this.setLocationRelativeTo(null);
        this.setLayout(null);
        this.setSize(500,400);
        this.setResizable(false);      
        
        ImageIcon image1=new ImageIcon(ClassLoader.getSystemResource("Images/Notepad.png"));
        Image img1=image1.getImage().getScaledInstance(100, 110, Image.SCALE_DEFAULT);
        ImageIcon image2=new ImageIcon(img1);
        JLabel img2=new JLabel(image2);
        img2.setBounds(200,20,100,110);
        this.add(img2);
        
        l1=new JLabel("Simple Notepad");
        l1.setFont(new Font("Trebuchet M3",Font.BOLD,25));
        l1.setForeground(new Color(0,0,128));
        l1.setBounds(150,150,200,30);
        this.add(l1);
        
        l2=new JLabel("<html>Notepad is a simple text editor for basic text editing program.It creates and edits plain text documents.</html>");
        l2.setFont(new Font("Trebuchet M3",Font.PLAIN,20));
        l2.setForeground(new Color(0,0,128));
        l2.setBounds(50,190,400,100);
        this.add(l2);
        
        l3=new JLabel("<html>Creater : Skylar Kyi Shin Khant</html>");
        l3.setFont(new Font("Trebuchet M3",Font.PLAIN,15));
        l3.setForeground(new Color(215,0,64));
        l3.setBounds(60,320,200,30);
        this.add(l3);
        
        b1=new JButton("OK");
        b1.setFont(new Font("Trebuchet M3",Font.BOLD,15));
        b1.setForeground(new Color(0,0,128));
        b1.setBackground(Color.orange);
        b1.setBounds(340,320,80,30);
        b1.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent ae)
            {
                dispose();
            }
        });
        this.add(b1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NotepadAbout dialog = new NotepadAbout(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
