/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TourJava;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author steve
 */
public class Progress extends javax.swing.JFrame implements Runnable {

    Thread t;
    JPanel panel;
    JProgressBar pbar;
    JLabel img2,label,label1;
    DBConnection con;
    ImageIcon logo=new ImageIcon(getClass().getClassLoader().getResource("Images/TravelLogo.png"));
    
    /**
     * Creates new form Progress
     */
    public Progress() {
        initComponents();
        this.setIconImage(logo.getImage());
        this.setTitle("Travel Agent System");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLayout(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setFocusable(true);
        
        panel=new JPanel();
        this.setContentPane(panel);
        
        ImageIcon image1=new ImageIcon(ClassLoader.getSystemResource("Images/Progress.jpeg"));
        Image img1=image1.getImage().getScaledInstance(1600, 1000, Image.SCALE_DEFAULT);
        ImageIcon image2=new ImageIcon(img1);
        img2=new JLabel(image2);
        panel.add(img2);
        
        label=new JLabel("System of Travel Agent");
        label.setFont(new Font("Trebuchet M3",Font.BOLD, 50));
        label.setForeground(Color.white);
        label.setBounds(500,50,800,60);
        img2.add(label);
         
        pbar=new JProgressBar(0,100);
        pbar.setFont(new Font("Trebuchet M3",Font.BOLD, 25));
        pbar.setBounds(300,700,1000,40);
        pbar.setStringPainted(true);
        img2.add(pbar);
        
        label1=new JLabel("Press SPACE to Continue");
        label1.setFont(new Font("Trebuchet M3",Font.PLAIN,25));
        label1.setForeground(new Color(215,0,64));
        label1.setBounds(650,700,500,40);
        label1.setVisible(false);
        img2.add(label1);
        
        t=new Thread(this);
        t.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Progress().setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        for(int i=0; i<=110; i+=10)
        {
            int m=pbar.getMaximum();
            if(i>m)
            {
                
                this.addKeyListener(new KeyAdapter(){
                    public void keyPressed(KeyEvent e)
                    {
                        if(e.getKeyCode()==KeyEvent.VK_SPACE)
                        {
                            new LogIn().setVisible(true);
                            dispose();
                        }
                    }
                });                
                pbar.setVisible(false);
                while(true)
                {
                    label1.setVisible(true);
                    try
                    {
                        Thread.sleep(500);
                    }
                    catch(Exception e){}

                    label1.setVisible(false);
                    try
                    {
                        Thread.sleep(500);
                    }
                    catch(Exception e){}
                }
            }
            else if(i<60)
            {
                pbar.setValue(i);
                pbar.setString("Loading...");
            }
            else if(i>=60)
            {
                pbar.setValue(i);
                pbar.setString("Wait For A Moment...");
            }
            try
            {
                Thread.sleep(500);
            }
            catch(Exception e) {}
        }
    }
}
